# Generated by Django 3.1.6 on 2021-03-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('auther_name', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='issueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_book_name', models.CharField(max_length=100)),
                ('reader_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginmodule.reader')),
            ],
        ),
    ]
