# Generated by Django 3.1.6 on 2021-03-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0003_auto_20210303_1324'),
        ('Bookmodule', '0003_issuebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther_name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='issue_book_name',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookmodule.book'),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='reader_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginmodule.reader'),
        ),
    ]
