# Generated by Django 3.1.6 on 2021-03-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmodule', '0004_auto_20210304_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='book_id',
            new_name='issue_id',
        ),
    ]
