# Generated by Django 3.1.5 on 2021-03-04 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmodule', '0005_auto_20210304_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
