# Generated by Django 3.1.6 on 2021-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmodule', '0006_issuebook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_book_available',
            field=models.BooleanField(default=True),
        ),
    ]
