# Generated by Django 3.1.6 on 2021-03-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmodule', '0007_book_is_book_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='date',
            new_name='issue_date',
        ),
    ]
