# Generated by Django 3.1.5 on 2021-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
