# Generated by Django 3.1.5 on 2021-02-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('auther_name', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
